### ISSUE TITLE
Crash in library

### ISSUE THREAD

**Issue by KITSSebSkuse** [Tealium/tealium-ios#111]
Hi,

We're seeing quite a few (30+ a day) crashes coming from the Tealium library. I was hoping that upgrading to the latest released version would fix this, but it doesn't appear to have.

The stack traces all look something like this:

```
OS Version: iOS 12.3.1 (16F203)
Report Version: 104

Exception Type: EXC_BAD_ACCESS (SIGBUS)
Exception Codes: BUS_NOOP at 0x00000003864dcce0
Crashed Thread: 0

Application Specific Information:
isEqualToString: > name >
Attempted to dereference garbage pointer 0x3864dcce0.

Thread 0 Crashed:
0   libobjc.A.dylib                 0x370214e30         objc_retain
1   TealiumIOS                      0x104286940         <redacted>
2   TealiumIOS                      0x104287138         <redacted>
3   TealiumIOS                      0x104287f20         <redacted>
4   TealiumIOS                      0x10426c2e0         <redacted>
5   WebKit                          0x392ae866c         _ZN3WTF8FunctionIFvRKNS_6VectorIN7WebCore6CookieELm0ENS_15CrashOnOverflowELm16EEEEE15CallableWrapperIZ35-[WKHTTPCookieStore getAllCookies:]E3$_5E4callES7_
6   WebKit                          0x392bf7d90         WTF::Function<T>::CallableWrapper<T>::call
7   WebKit                          0x392b68294         WebKit::GenericCallback<T>::performCallbackWithReturnValue
8   WebKit                          0x392b68114         WebKit::WebCookieManagerProxy::didGetCookies
9   WebKit                          0x392d66644         IPC::callMemberFunctionImpl<T>
10  WebKit                          0x392d6633c         IPC::handleMessage<T>
11  WebKit                          0x3929e4ce8         IPC::MessageReceiverMap::dispatchMessage
12  WebKit                          0x392c62c68         WebKit::NetworkProcessProxy::didReceiveMessage
13  WebKit                          0x3929d7e60         IPC::Connection::dispatchMessage
14  WebKit                          0x3929d4bfc         IPC::Connection::dispatchMessage
15  WebKit                          0x3929d81f4         IPC::Connection::dispatchOneIncomingMessage
16  JavaScriptCore                  0x382ddd1c4         WTF::RunLoop::performWork
17  JavaScriptCore                  0x382ddd494         WTF::RunLoop::performWork
18  CoreFoundation                  0x372a43440         __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
19  CoreFoundation                  0x372a433bc         __CFRunLoopDoSource0
20  CoreFoundation                  0x372a42c78         __CFRunLoopDoSources0
21  CoreFoundation                  0x372a3d94c         __CFRunLoopRun
22  CoreFoundation                  0x372a3d250         CFRunLoopRunSpecific
23  GraphicsServices                0x37664cd88         GSEventRunModal
24  UIKitCore                       0x21d7c44bc         UIApplicationMain
25  OurAppHere                      0x2023f97ec         main (main.swift:13)
26  libdyld.dylib                   0x37101cfd4         start
```

There's a fairly consistent distribution between device & OS versions. Looking at the exception message and the stack trace it _looks_ like it's trying to retrieve a set of cookies, check their names are a given string, and blowing up because the cookie object has been deallocated. It's difficult to tell exactly as it doesn't look like we've got adequate symbols to resolve the frames inside Tealium.

Is this a known issue with any available workarounds, or if not could I request this be looked into?

Thanks!

**Comment by craigrouse** [comment]
@KITSSebSkuse We hoped that recent updates had squashed this 🐛, so sorry to hear you're still having trouble with it.

We will look into this and try and come up with a solution ASAP.

We'll get back to you if we need any further info.

**Comment by craigrouse** [comment]
@KITSSebSkuse just to verify, this is with v 5.5.2 of the TealiumIOS library?

**Comment by KITSSebSkuse** [comment]
@craigrouse Correct, we're seeing this with 5.5.2. It seems to have been happening for a little while, but upgrading to 5.5.2 doesn't seem to have had an impact.

**Comment by KITSDavidHardiman** [comment]
Hi @craigrouse, any update on your investigation?

**Comment by KITSDavidHardiman** [comment]
Hi @craigrouse, any update? This is a major issue for us that's affecting our app and we need an update asap.

**Comment by craigrouse** [comment]
@KITSDavidHardiman @KITSSebSkuse We are working on it. 

Regarding the debug symbols, we do provide these on our GitHub repo, so you should be able to upload them to your crash tracking tool and see exactly which line is crashing. If you have a chance to do this, you can send your symbolicated logs over to support@tealium.com for my attention.

If you would like to resolve this issue in the short term, you could consider going back to UIWebView which doesn't have this issue. Please see here for documentation on this: https://docs.tealium.com/platforms/ios/tag-management/#about-uiwebview

We will aim to provide an update on this issue later today.

**Comment by KITSDavidHardiman** [comment]
@craigrouse Those symbols won't help, the library gets re-processed by Apple when Apple compiles from bitcode. For some reason the symbols from Apple don't include those for your library though. Out of interest, why does UIWebView not exhibit the problem? Also out of interest, have you considered providing this library as source? You do that for your swift version it seems.

**Comment by KITSDavidHardiman** [comment]
@craigrouse https://github.com/Tealium/tealium-ios/issues/104#issuecomment-498456358 suggests that switching back to UIWebView doesn't fix the issue?

**Comment by craigrouse** [comment]
@KITSDavidHardiman I believe that was a separate issue, and we did add some mitigation against that crash in the latest version.

The logic in question copies cookies over during the migration from UIWebView to WKWebView. This is a one-time copy, and avoids losing any cookies that analytics tags were relying on (otherwise you'd have 100% new visitors). This is why switching back to UIWebView should solve this problem.

If you can send the unsymbolicated logs over to our support address, we can symbolicate them on our end also.

Open source is on our roadmap. I can't say any more than that at this point, but watch this space.

**Comment by KITSDavidHardiman** [comment]
@craigrouse You've got the unsymbolicated log in the issue. My colleague posted in the original message.

**Comment by craigrouse** [comment]
@KITSDavidHardiman you're right - my apologies. I was hoping you might have the full log file, but this should be good enough. Leave it with me.

**Comment by craigrouse** [comment]
@KITSDavidHardiman @KITSSebSkuse if you wouldn't mind, please send an email to our support address, if you haven't already, and let us know which Tealium client you're working on behalf of, referencing this issue? Thank you in advance.

**Comment by KITSDavidHardiman** [comment]
Done

**Comment by craigrouse** [comment]
Appreciate it - thanks @KITSDavidHardiman. We have it.

**Comment by christinasund** [comment]
@KITSDavidHardiman @KITSSebSkuse Thanks for your patience on this. Unfortunately, we have not been able to reproduce the crash on our end or find any clues that would help us confidently implement a proper solution at this point. We did receive the full log, thank you, but they didn't come through as symbolicated and we couldn't do this on our end without the app. Since a timely resolution is of utmost importance, we recommend the following while we continue to investigate:

1. Upgrade to version 5.5.4 - We have made some additional WKWebView optimizations that might help your case. Here is what we changed: UIView auto-detection logic for WKWebView has been improved, which should account for most cases with complex view hierarchies, without the need to manually pass a UIView instance in the WebView config. Validation in your own app is essential; verify that you can see tracking calls leaving your app in a variety of different screens in your app, including any views that may be launched from push notifications, where the view hierarchy may have changed.

2. Fallback to using the legacy UIWebView by setting the TEALConfiguration flag .useLegacyWebView to YES ([more info here](https://community.tealiumiq.com/t5/Installation-Libraries/Debugging-Tealium-Mobile-Apps/ta-p/15508))

In the meantime, what will help us is a way to consistently reproduce this crash on our end and/or the symbolicated logs. Preferably both if possible :)

We sincerely apologize for any and all inconvenience this has caused and are doing our best to squash the WKWebView bugs as they arise. 

Thanks again.

**Comment by KITSDavidHardiman** [comment]
Hi @christinasund. Unfortunately we have no way to consistently reproduce the crash, it's just visible in our crash reporting tool, and is hugely prevalent in our app at the moment for a large number of users. As I've mentioned previously, for some reason apple aren't giving us dSyms for the Tealium library after processing the bitcode. I've no idea why. That's why I asked about whether it might be possible to supply the library as source code, so we might stand a better chance of understanding the crash, as well as potentially helping you in fixing it.

1. We'll upgrade to 5.5.4 today. I'm not sure what you're suggesting will make much difference. I don't think we pass a UIView instance to anything anyway. We try not to let analytics libraries do anything "automatically" if we can. It's better to remain in control. That said, if your "auto-detection" logic uses method swizzling, we will likely turn that off anyway.

2. I've enabled that flag ready for our next release. If I understand correctly the reason this fallback might work, I'm not 100% convinced by it, but it's worth a go.

**Comment by KITSDavidHardiman** [comment]
@christinasund @craigrouse The Carthage feed at https://tags.tiqcdn.com/dle/tealiummobile/tealium-ios-carthage/tealium-carthage.json hasn't been updated for 5.5.4.

**Comment by craigrouse** [comment]
@KITSDavidHardiman I've just published the Carthage file.

**Comment by KITSDavidHardiman** [comment]
@craigrouse  How long do your caches usually take to clear? Still seeing 5.5.3

**Comment by craigrouse** [comment]
@KITSDavidHardiman try a hard reload now (and if you don't see it, add a cachebuster on the end `?_cb=234dgdfg` - just some random string)

**Comment by KITSDavidHardiman** [comment]
Ok

**Comment by KITSDavidHardiman** [comment]
@craigrouse Just updated using the carthage update and the info.plist file in the framework still says 5.5.3. Is that just an oversight or has the carthage update downloaded the wrong thing?

**Comment by craigrouse** [comment]
@KITSDavidHardiman Just checked, and the plists are updated in the source. I'd suggest clearing Carthage cache and trying again. Just about to do a check on my end too with Carthage to make sure there are no issues.

**Comment by KITSDavidHardiman** [comment]
@craigrouse I've downloaded the zip file manually and it's definitely 5.5.3 in there.

**Comment by craigrouse** [comment]
@KITSDavidHardiman I see the same thing, but it is definitely 5.5.4. We actually get the version from a constant, so when you trigger a tracking call with the new library, you should see `tealium_library_version` = 5.5.4 in the payload. We will get the plist corrected later.

**Comment by KITSDavidHardiman** [comment]
Fair enough. Good to know.

**Comment by KITSSebSkuse** [comment]
Just to keep you updated, we shipped a version with `useLegacyWebView` = `true`, a couple of days ago and haven't seen a crash in it, so I'm going to say that's 'fixed' it for us.

**Comment by glenyi-rue** [comment]
We're on Tealium iOS SDK 5.3.2 and would like to update to deprecate all uses of UIWebView (legacy), but this crash is concerning. Is a fix being investigated?

**Comment by jonathanswong** [comment]
@glenyi-rue This should be fixed in the latest TealiumIOS 5.5.5 release. We also have the [tealium-swift](https://github.com/tealium/tealium-swift) library if that suits your needs.

**Comment by christinasund** [comment]
Closing due to inactivity, let us know if the problem persists
